### PR TITLE
Fixed string::replace doesn't replace multiple occurrences of longer string with shorter one 

### LINKED ISSUE #199: String::replace doesn't work when replacing multiple occurencies of longer String by shorter one
```
TEST_CASE ("Testing String::replace(String, String) substr 'find' smaller than 'replace' multiple occurencies", "[String-replace-08]")
{
  arduino::String str("Hello Arduino! Hello, Hello, Hello");
  str.replace(arduino::String("ll"), arduino::String("lll"));
  REQUIRE(str == "Helllo Arduino! Helllo, Helllo, Helllo");
}

TEST_CASE ("Testing String::replace(String, String) substr 'find' same length as 'replace' multiple occurencies", "[String-replace-09]")
{
  arduino::String str("Hello Arduino! Hello, Hello, Hello");
  str.replace(arduino::String("ll"), arduino::String("11"));
  REQUIRE(str == "He11o Arduino! He11o, He11o, He11o");
}

TEST_CASE ("Testing String::replace(String, String) substr 'find' larger than 'replace' multiple occurencies", "[String-replace-10]")
{
  arduino::String str("Helllo Arduino! Helllo, Helllo, Helllo");
  str.replace(arduino::String("lll"), arduino::String("ll"));
  REQUIRE(str == "Hello Arduino! Hello, Hello, Hello");
}
```

The last testcase fails as it doesn't replace anything at all. Other two works as expected.

Reported in https://github.com/arduino/ArduinoCore-megaavr/issues/109

### PR DESCRIPTION
**Pull request by PiotrekB416**
This pr fixes `string::replace` not replacing multiple occurrences of longer string with shorter one.
I also included unit tests from the issue

This fixes #199

### CODE REVIEW

File: api/String.cpp [hunk 1]
```diff
@@ -652,9 +652,9 @@ void String::replace(const String& find, const String& replace)
 		}
 	} else if (diff < 0) {
 		unsigned int size = len; // compute size needed for result
+        diff = 0 - diff;
```
Comment (per1234) [inline api/String.cpp:655]:
```suggestion
		diff = 0 - diff;
```

Use tabs for indentation to be consistent with the established code style of the file.

**Review by per1234 — CHANGES_REQUESTED** [review]

File: api/String.cpp [hunk 2]
```diff
@@ -652,9 +652,9 @@ void String::replace(const String& find, const String& replace)
 		}
 	} else if (diff < 0) {
 		unsigned int size = len; // compute size needed for result
+		diff = 0 - diff;
```
Comment (aentinger) [inline api/String.cpp:655]: Ah, this line hurts 😉 . (Could it not be `abs(diff)`? However, you did not commit this crime, simply moved the line to the right position 👍 .

**Review by aentinger — APPROVED** [review]
Excellent work, thank you @PiotrekB416 🚀
